name: Feature request
description: Idea or improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem to solve
  - type: textarea
    attributes:
      label: Proposed solution
  - type: textarea
    attributes:
      label: Alternatives considered
